### ISSUE TITLE
0 or NA?

### ISSUE THREAD

**Issue by thoree** [magnusdv/ribd#5]
I'm not sure I understand when 0 or NA-s are returned from
`condensedIdentityX`. Could one argue that the rowsums of the returned matix should
add to 1 (?) and that therefore 0 is more reasonable than NA-s in e.g.
``` r
library(ribd, quietly = TRUE)
#> 
#> Attaching package: 'ribd'
#> The following object is masked from 'package:base':
#> 
#>     kappa
x = nuclearPed(1)
condensedIdentityX(x, c(3,3)) 
#> [1]  1  0 NA NA NA NA NA NA NA
```

<sup>Created on 2019-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
I agree that the documentation needs improvement here. 

The Value section of  `?condensedIdentityX` currently says:

> If ids has length 2: A vector of length 9, containing the condensed identity coefficients. If any of the individuals are male, certain states are undefined, and the corresponding coefficients are NA.

What I think *should* be included in the description would be along the following lines:
* Since males are hemizygous on X, the 9 autosomal identity states with 2 alleles for each individual do not accurately describe the picture on X.
* However, for a given pair of sexes (e.g. female-female, female-male, male-female, male-male), each X state corresponds in a natural way to one of the autosomal states, in the following way:
**Replace the single allele of any male, with a pair of autozygous alleles for that individual.**
* In other words, the (autosomal) states that are undefined on X are the ones involving a male with two non-IBD alleles.

The main advantage of this approach is that one can re-use most of the code producing the output, and (even more importantly, I think) that one can still refer to the standard ordering of the 9 states as used by Jacquard, without having to draw any new pictures or learn new names/orders of states for each sex combination.

In your example, with both individuals male, only states 1 and 2 are well defined, and the rest are NA.

Finally, I see your point that one could use 0 instead of NA, but I disagree for two reasons: 
1) I find the NA's quite useful, both for testing purposes and in interactive use (as a quick check that the input was as intended).
2) As for summing to 1, this should be trivial using na.rm = TRUE.

Do you think the above explanation would be satisfactory?
